### ISSUE TITLE
Error when compiling using Angular 5.0.0

### ISSUE THREAD

**Issue by ppennings** [stevepapa/ng-autosize#12]
I just upgraded to Angular 5.0.0 and when I compile I get the following error:

ERROR in ./node_modules/ng-autosize/index.ts
Module build failed: Error: /Users/ppennings/Develop/NIS-frontend/node_modules/ng-autosize/index.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (/Users/ppennings/Develop/NIS-frontend/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:629:23)
    at plugin.done.then (/Users/ppennings/Develop/NIS-frontend/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/app/shared/shared.module.ts 47:0-39
 @ ./src/app/upload-asset/upload-asset.module.ts
 @ ./src/$$_lazy_route_resource lazy
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by aarongranade** [comment]
Use the following import line in your module:

import { Autosize } from 'ng-autosize/src/autosize.directive';

**Comment by mtabaj** [comment]
Still not working for me.
With your suggestion the error is just a little different

[0] ERROR in ./node_modules/ng-autosize/src/autosize.directive.ts
[0] Module build failed: Error: C:\-  vv\vv-pro\node_modules\ng-autosize\src\autosize.directive.ts is not part of the compilation output. Please check the other error messages for details.
[0]     at AngularCompilerPlugin.getCompiledFile (C:\-  vv\vv-pro\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:629:23)
[0]     at plugin.done.then (C:\-  vv\vv-pro\node_modules\@ngtools\webpack\src\loader.js:467:39)
[0]     at <anonymous>
[0]     at process._tickCallback (internal/process/next_tick.js:188:7)
[0]  @ ./client/app/modules/schools/schools.module.ts 19:0-62
[0]  @ ./client/$$_lazy_route_resource lazy
[0]  @ ./node_modules/@angular/core/esm5/core.js
[0]  @ ./client/main.ts
[0]  @ multi webpack-dev-server/client?http://0.0.0.0:0 ./client/main.ts

**Comment by aarongranade** [comment]
Did you add Autosize in the declarations of the module as well?

**Comment by subatomicglue** [comment]
I have the following 2 items in my `app.module.ts`:

`import { Autosize } from 'ng-autosize/src/autosize.directive';`

```
@NgModule({
  declarations: [
    Autosize,
```

and I'm getting:

```
ERROR in ./node_modules/ng-autosize/src/autosize.directive.ts
Module build failed: Error: .../node_modules/ng-autosize/src/autosize.directive.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (.../node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:629:23)
    at plugin.done.then (..../node_modules/@ngtools/webpack/src/loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./src/app/app.module.ts 20:0-62
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```


Versions:
```
Angular CLI: 1.5.0
Node: 7.5.0
OS: darwin x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.2
typescript: 2.4.2
webpack: 3.8.1
```

Reading around, looks like it is invalid to package npm modules with the .ts files 
https://github.com/angular/angular-cli/issues/8284#issuecomment-341417325

**Comment by subatomicglue** [comment]
Happens on a fresh `ng new` project also

```
ng new myApp
npm install
npm install --save ng-autosize
*** edit app.module.ts to have the 2 edits above***
npm start

ERROR in ./node_modules/ng-autosize/src/autosize.directive.ts
Module build failed: Error: .../myApp/node_modules/ng-autosize/src/autosize.directive.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (.../myApp/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:629:23)
    at plugin.done.then (.../myApp/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./src/app/app.module.ts 10:0-62
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

```
Angular CLI: 1.5.0
Node: 7.5.0
OS: darwin x64
Angular: 5.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.2
typescript: 2.4.2
webpack: 3.8.1
```

**Comment by subatomicglue** [comment]
It is (now in Angular5) invalid to package npm modules without .js files (with only the .ts files)
https://github.com/angular/angular-cli/issues/8284#issuecomment-341417325

To work around this I have had to do this in `tsconfig.app.json`
```
  "include": [ "../node_modules/ng-autosize/**/*.ts", "**/*.ts" ],
```

Previously I did not have an `include` line in my `tsconfig.app.json`.

From reading the above link, it seems that the *correct* fix is to package `ng-autosize` with `.js` files... looking in the `ng-autosize` module directory I do not see `.js` files:

```
> ls -lR ng-autosize/

total 48
drwxr-xr-x    9 me  staff    306 Nov 10 09:24 .
drwxr-xr-x  924 me  staff  31416 Nov 10 09:25 ..
-rw-r--r--    1 me  staff     29 Oct  3 22:08 .npmignore
-rw-r--r--    1 me  staff   1098 Oct  3 22:08 LICENSE
-rw-r--r--    1 me  staff   1306 Oct 15 19:41 README.md
-rw-r--r--    1 me  staff    146 Oct  3 22:08 index.ts
-rw-r--r--    1 me  staff   2560 Nov 10 09:24 package.json
drwxr-xr-x    3 me  staff    102 Oct 15 19:32 src
-rw-r--r--    1 me  staff    267 Oct  3 22:08 tsconfig.json

ng-autosize//src:
total 8
drwxr-xr-x  3 me  staff   102 Oct 15 19:32 .
drwxr-xr-x  9 me  staff   306 Nov 10 09:24 ..
-rw-r--r--  1 me  staff  2293 Oct 15 19:32 autosize.directive.ts
```

**Comment by shyamal890** [comment]
+1

**Comment by martinduris** [comment]
Still no luck with solving this issue ?

**Comment by koljada** [comment]
+1

**Comment by stevepapa** [comment]
Major rewrite/refactor completed. Project updated to Angular19. No longer applicable, please create new issue if defect found. Thank you.
