### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by bhavincb** [stevepapa/ng-autosize#4]
after installing on ionic project i get this error.
i had imported Autosize in app.module.ts and added entry in declaration and entry point.

Error: ./node_modules/ng-autosize/index.ts
Module build failed: Error: ENOENT: no such file or directory, open '\node_modules\ng-autosize\index.js'
    at Error (native)
 @ ./src/app/app.module.ts 7:0-39
 @ ./src/app/main.ts
    at BuildError.Error (native)
    at new BuildError (\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at callback (\node_modules\@ionic\app-scripts\dist\webpack.js:119:28)
    at emitRecords.err (\node_modules\webpack\lib\Compiler.js:269:13)
    at Compiler.emitRecords (\node_modules\webpack\lib\Compiler.js:375:38)
    at emitAssets.err (\node_modules\webpack\lib\Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (\node_modules\webpack\lib\Compiler.js:368:12)
    at next (\node_modules\tapable\lib\Tapable.js:218:11)
    at Compiler.compiler.plugin (\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (\node_modules\tapable\lib\Tapable.js:222:13)

**Comment by stevepapa** [comment]
Do you have a code sample? Errors like this usually occur from name mismatch due to case sensitivity. Check the case of your import statements and declarations.

**Comment by bhavincb** [comment]
Inside the app.module.ts

import {Autosize} from 'ng-autosize';

And added "Autosize" to declarations

**Comment by hkashlan** [comment]
it happened for me with ionic2

BTW I followed instructions from  https://stevepapa.com/ng-autosize/

**Comment by bhavincb** [comment]
Ionic latest version 3.6.1

**Comment by mkhoshnasib** [comment]
It happend for me too in ionic 3.6.x

**Comment by mydoal** [comment]
Happened for me too. Looking for index.js instead of index.ts.
Any updates on this issue?

Ionic 3.19

**Comment by hkeio** [comment]
With angular 5.2.0

```
./node_modules/ng-autosize/index.ts
Module build failed: Error: <project>/node_modules/ng-autosize/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
```

**Comment by stevepapa** [comment]
Major rewrite/refactor completed. Project updated to Angular19. No longer applicable, please create new issue if defect found. Thank you.
